plugins { id 'com.android.application' }

android {
    namespace 'com.fast.radio'
    compileSdk 36
    defaultConfig {
        applicationId 'com.fast.radio.final9'
        minSdk 23
        targetSdk 36
        versionCode 9
        versionName '9.0'
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.media3:media3-exoplayer:1.11.0'
    implementation 'androidx.media3:media3-exoplayer-hls:1.11.0'
    implementation 'androidx.media3:media3-exoplayer-dash:1.11.0'
    implementation 'androidx.media3:media3-session:1.11.0'
    implementation 'androidx.media3:media3-ui:1.11.0'
}
